package com.holkan.tracker.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.holkan.tracker.data.Tracking;

import com.holkan.tracker.data.TrackingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackingDaoConfig;

    private final TrackingDao trackingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackingDaoConfig = daoConfigMap.get(TrackingDao.class).clone();
        trackingDaoConfig.initIdentityScope(type);

        trackingDao = new TrackingDao(trackingDaoConfig, this);

        registerDao(Tracking.class, trackingDao);
    }
    
    public void clear() {
        trackingDaoConfig.getIdentityScope().clear();
    }

    public TrackingDao getTrackingDao() {
        return trackingDao;
    }

}
