package com.holkan.tracker.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRACKING.
 */
public class Tracking {

    private Long id;
    private Double lat;
    private Double lng;
    private Float speed;
    private Integer event;
    private java.util.Date datetime;
    private Float accuracy;

    public Tracking() {
    }

    public Tracking(Long id) {
        this.id = id;
    }

    public Tracking(Long id, Double lat, Double lng, Float speed, Integer event, java.util.Date datetime, Float accuracy) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
        this.speed = speed;
        this.event = event;
        this.datetime = datetime;
        this.accuracy = accuracy;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Integer getEvent() {
        return event;
    }

    public void setEvent(Integer event) {
        this.event = event;
    }

    public java.util.Date getDatetime() {
        return datetime;
    }

    public void setDatetime(java.util.Date datetime) {
        this.datetime = datetime;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

}
