package com.holkan.tracker.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRACKING.
 */
public class Tracking {

    private Long id;
    private Double lat;
    private Double lng;
    private Integer speed;
    private Byte event;
    private java.util.Date datetime;
    private Float accuracy;
    private String provider;
    private Boolean active_gps;
    private Integer battery;
    private Integer satellites;
    private Boolean active_gprs;

    public Tracking() {
    }

    public Tracking(Long id) {
        this.id = id;
    }

    public Tracking(Long id, Double lat, Double lng, Integer speed, Byte event, java.util.Date datetime, Float accuracy, String provider, Boolean active_gps, Integer battery, Integer satellites, Boolean active_gprs) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
        this.speed = speed;
        this.event = event;
        this.datetime = datetime;
        this.accuracy = accuracy;
        this.provider = provider;
        this.active_gps = active_gps;
        this.battery = battery;
        this.satellites = satellites;
        this.active_gprs = active_gprs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Integer getSpeed() {
        return speed;
    }

    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    public Byte getEvent() {
        return event;
    }

    public void setEvent(Byte event) {
        this.event = event;
    }

    public java.util.Date getDatetime() {
        return datetime;
    }

    public void setDatetime(java.util.Date datetime) {
        this.datetime = datetime;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public Boolean getActive_gps() {
        return active_gps;
    }

    public void setActive_gps(Boolean active_gps) {
        this.active_gps = active_gps;
    }

    public Integer getBattery() {
        return battery;
    }

    public void setBattery(Integer battery) {
        this.battery = battery;
    }

    public Integer getSatellites() {
        return satellites;
    }

    public void setSatellites(Integer satellites) {
        this.satellites = satellites;
    }

    public Boolean getActive_gprs() {
        return active_gprs;
    }

    public void setActive_gprs(Boolean active_gprs) {
        this.active_gprs = active_gprs;
    }

}
